import { MigrationInterface, QueryRunner } from "typeorm";

export class FakeFeeds1609691898779 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`insert into feed ("title", "imageUrl", "creatorId") values ('Marked for Death', 'http://google.co.jp/montes/nascetur/ridiculus/mus/etiam.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Dogville', 'http://github.com/malesuada.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('From the Journals of Jean Seberg', 'http://devhub.com/sagittis/sapien/cum/sociis/natoque/penatibus.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Civil War, The', 'http://themeforest.net/diam.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Paris', 'https://hao123.com/condimentum/id/luctus/nec/molestie/sed/justo.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Moneyball', 'https://wikispaces.com/massa/donec/dapibus/duis.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('I Know What I Saw', 'http://gnu.org/aenean/auctor/gravida.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Who''s That Knocking at My Door?', 'https://dagondesign.com/donec/dapibus/duis/at.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Close Encounters of the Third Kind', 'https://unesco.org/libero/quis/orci.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Evil Aliens', 'http://woothemes.com/libero/non/mattis.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Journey to the Beginning of Time', 'https://discuz.net/in/libero/ut/massa/volutpat/convallis/morbi.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Trilogy: The Weeping Meadow (Trilogia: To livadi pou dakryzei)', 'https://abc.net.au/congue.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('All the Light in the Sky', 'http://biglobe.ne.jp/sollicitudin/ut/suscipit/a/feugiat/et/eros.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Great Ziegfeld, The', 'http://spotify.com/vestibulum/quam/sapien/varius/ut/blandit/non.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Fulltime Killer (Chuen jik sat sau)', 'http://google.com/enim/sit/amet/nunc.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Good Boy!', 'https://forbes.com/pulvinar/sed/nisl/nunc/rhoncus.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Grin Without a Cat, A (Fond de l''air est rouge, Le)', 'http://forbes.com/sapien/urna/pretium/nisl.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Glimmer Man, The', 'https://symantec.com/leo/maecenas/pulvinar/lobortis/est.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Stand Up and Cheer!', 'http://youku.com/commodo/vulputate/justo/in/blandit/ultrices/enim.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Kentucky Fried Movie, The', 'http://earthlink.net/dui/vel/nisl/duis/ac/nibh/fusce.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Swan, The', 'http://addthis.com/rutrum/at/lorem/integer/tincidunt/ante/vel.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Eight Deadly Shots (Kahdeksan surmanluotia)', 'http://statcounter.com/sagittis/nam/congue/risus/semper.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Mother of Mine (Äideistä parhain)', 'http://reverbnation.com/vehicula/consequat.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('No Small Affair', 'https://uiuc.edu/cras/non/velit.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Americano', 'https://tumblr.com/morbi/non/quam/nec/dui/luctus/rutrum.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('First Snow', 'http://youtube.com/luctus/et.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Little Secrets', 'http://answers.com/et/ultrices/posuere/cubilia.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Texas Chainsaw Massacre: The Next Generation (a.k.a. The Return of the Texas Chainsaw Massacre)', 'http://yale.edu/tincidunt/eget/tempus/vel/pede/morbi/porttitor.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Tarnation', 'http://admin.ch/ut/erat/id/mauris/vulputate/elementum.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Searching for Sugar Man', 'http://google.cn/lacus.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Pet Sematary II', 'https://google.ca/donec.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Tron: Legacy', 'http://jigsy.com/leo/rhoncus/sed/vestibulum/sit.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('White Massai, The (Weisse Massai, Die)', 'https://addthis.com/pulvinar.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Learning to Ride', 'http://google.ru/condimentum/curabitur/in/libero/ut/massa.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Ride in the Whirlwind', 'http://upenn.edu/mauris/ullamcorper/purus/sit.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Miami Blues', 'http://php.net/massa/quis/augue/luctus/tincidunt/nulla/mollis.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Going Hollywood', 'http://bloomberg.com/sodales/scelerisque/mauris/sit/amet.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Valhalla Rising', 'http://biglobe.ne.jp/lacinia/sapien/quis/libero/nullam/sit.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Elevator Girl', 'http://chronoengine.com/eu/magna/vulputate/luctus/cum/sociis.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Sleepy Time Gal, The', 'https://bing.com/congue/elementum.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Pharaoh''s Army', 'http://accuweather.com/erat/quisque/erat/eros/viverra/eget.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Purple Plain, The', 'https://google.ca/pretium/iaculis/justo.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Cabeza de Vaca', 'https://yahoo.com/fusce/posuere/felis/sed.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Bullet', 'http://blogger.com/nunc.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Free to Play', 'https://msn.com/posuere/cubilia/curae/donec.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Sunshine on Leith ', 'https://tuttocitta.it/sit/amet/eleifend/pede/libero.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Street Smart', 'http://artisteer.com/in/hac.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Belle', 'https://e-recht24.de/donec/ut/dolor/morbi/vel/lectus.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Babylon', 'https://gov.uk/mus/vivamus/vestibulum/sagittis/sapien/cum.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Miller''s Crossing', 'https://spotify.com/primis/in/faucibus/orci/luctus/et.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Tea For Two', 'https://nytimes.com/bibendum/felis/sed/interdum/venenatis/turpis/enim.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Snake in the Eagle''s Shadow (Se ying diu sau)', 'https://exblog.jp/tellus/in/sagittis/dui/vel/nisl/duis.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Enchantment', 'http://histats.com/tincidunt/eu.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Silence of the Sea, The (Le silence de la mer)', 'http://dmoz.org/amet/eros/suspendisse/accumsan/tortor/quis.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Torch Song', 'http://illinois.edu/imperdiet/et/commodo/vulputate.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Going Hollywood', 'http://cyberchimps.com/lacus/purus.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Forever Mine', 'https://examiner.com/quis/turpis/sed/ante.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Boys', 'http://umich.edu/magna.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Loneliness of the Long Distance Runner, The', 'https://so-net.ne.jp/enim/sit/amet/nunc/viverra.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Children of the Corn II: The Final Sacrifice', 'https://google.com/morbi/porttitor/lorem/id/ligula.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Catered Affair, The', 'http://yellowbook.com/elementum/pellentesque/quisque/porta/volutpat.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Milius', 'https://berkeley.edu/natoque/penatibus/et/magnis/dis/parturient/montes.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('At Sword''s Point', 'https://seesaa.net/platea/dictumst.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Rudy', 'https://w3.org/libero/ut/massa.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Number 23, The', 'http://51.la/lectus/vestibulum/quam/sapien/varius/ut/blandit.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Prairie Love', 'https://youtube.com/morbi/ut/odio/cras/mi/pede.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('The Captains', 'http://netscape.com/praesent/blandit/lacinia/erat.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Red Tent, The (Krasnaya palatka)', 'http://reddit.com/ante/vestibulum/ante/ipsum/primis/in/faucibus.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Ikiru', 'https://wsj.com/nibh/in/quis/justo/maecenas/rhoncus/aliquam.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Story of Science, The', 'http://nhs.uk/quam.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('State and Main', 'http://wix.com/ut/blandit/non/interdum/in.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Cycling with Moliere (Alceste à bicyclette)', 'https://myspace.com/fusce/congue/diam.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Best Man, The', 'http://bbb.org/ut/ultrices/vel/augue.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('PressPausePlay', 'https://printfriendly.com/et.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Gasland Part II', 'https://state.tx.us/ac/consequat.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Autohystoria', 'https://jalbum.net/velit.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Bitch, The (La chienne)', 'http://mediafire.com/nonummy/maecenas/tincidunt/lacus/at.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Grandma''s Boy', 'https://wordpress.com/dui/nec/nisi/volutpat/eleifend/donec/ut.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Golden Gate', 'http://accuweather.com/in/felis/donec/semper/sapien.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Scapegoat, The', 'https://apache.org/nam/dui/proin/leo/odio.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('How Hitler Lost the War', 'http://boston.com/ante/vel/ipsum/praesent.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Dragon ball Z 04: Lord Slug', 'https://wikispaces.com/ultrices/aliquet/maecenas/leo/odio/condimentum/id.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Liberal Arts', 'https://time.com/ullamcorper/augue/a.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Liar Liar', 'https://house.gov/bibendum/felis/sed.html', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Fort McCoy', 'http://friendfeed.com/turpis/sed/ante/vivamus.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Ghost in the Shell 2: Innocence (a.k.a. Innocence) (Inosensu)', 'http://moonfruit.com/iaculis/congue/vivamus/metus/arcu/adipiscing/molestie.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Beautiful Person, The (La belle personne)', 'http://nasa.gov/justo/sit.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('RV', 'https://buzzfeed.com/accumsan/felis/ut.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Scooby-Doo! The Mystery Begins', 'http://biblegateway.com/justo/in.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Cell 211 (Celda 211)', 'http://salon.com/nisi/vulputate/nonummy/maecenas/tincidunt.xml', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('My Father the Hero (Mon père, ce héros.)', 'https://live.com/cubilia/curae/nulla/dapibus/dolor/vel/est.json', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Flandres (Flanders)', 'http://storify.com/accumsan/tortor.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Suddenly, Last Summer', 'http://dailymotion.com/nam/ultrices/libero.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Love, Money, Love', 'https://hexun.com/consequat/varius/integer/ac.aspx', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Houseguest', 'http://soup.io/primis/in/faucibus/orci.js', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Beer for My Horses', 'https://storify.com/fermentum/justo/nec/condimentum/neque.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Death on the Nile', 'http://arstechnica.com/amet/justo/morbi.jpg', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Two Weeks Notice', 'https://fema.gov/diam/cras/pellentesque/volutpat/dui.png', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Apartment Zero', 'https://newyorker.com/eget/elit.jsp', 2);
    insert into feed ("title", "imageUrl", "creatorId") values ('Circle of Deception, A', 'http://spotify.com/amet/turpis/elementum/ligula.html', 2);
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
