import { MigrationInterface, QueryRunner } from "typeorm";

export class MockFeeds1609702083044 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('What We Did on Our Holiday', 'http://hhs.gov/in/magna/bibendum/imperdiet/nullam/orci/pede.json', 2, '2020-12-14T17:54:43Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('We Bought a Zoo', 'http://cbc.ca/felis/sed/lacus/morbi/sem/mauris.jpg', 2, '2020-01-11T02:11:57Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Brothers O''Toole, The', 'https://answers.com/ut/ultrices.jsp', 2, '2020-01-25T04:07:11Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Privilege', 'https://blogger.com/pulvinar/sed/nisl/nunc/rhoncus.jsp', 2, '2020-09-12T00:08:24Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Gunfighters', 'https://unblog.fr/leo/pellentesque/ultrices/mattis/odio/donec.png', 2, '2020-01-31T13:38:10Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Body Fat Index of Love', 'https://mediafire.com/enim/blandit/mi/in.js', 2, '2020-01-13T10:54:54Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Runaway', 'http://hibu.com/lorem/ipsum.xml', 2, '2020-03-20T19:02:33Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Lamerica', 'https://creativecommons.org/mauris/vulputate/elementum/nullam/varius/nulla.jsp', 2, '2020-04-22T09:21:51Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('May', 'http://noaa.gov/quam/fringilla/rhoncus.jpg', 2, '2020-07-22T02:00:14Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('The Last Station', 'https://bizjournals.com/turpis/eget/elit/sodales/scelerisque.aspx', 2, '2020-03-20T03:27:37Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('My Friend Ivan Lapshin (Moy drug Ivan Lapshin)', 'http://feedburner.com/ipsum/ac/tellus/semper/interdum.xml', 2, '2020-01-26T15:41:05Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Zero Kelvin (Kjærlighetens kjøtere)', 'https://howstuffworks.com/ut.xml', 2, '2020-02-29T02:02:31Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Lovelace', 'https://umich.edu/curae/donec/pharetra/magna.xml', 2, '2020-03-07T01:03:07Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Fearless Hyena, The (Xiao quan guai zhao)', 'http://sciencedirect.com/potenti.html', 2, '2020-10-30T06:02:33Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Between the Folds', 'https://dedecms.com/nulla/elit.js', 2, '2020-01-18T02:18:44Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Pinocchio', 'http://dion.ne.jp/nisl/nunc.html', 2, '2020-05-24T03:41:57Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Valley of the Dragons', 'http://wufoo.com/aliquam/augue.jpg', 2, '2020-01-04T13:20:33Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Magic Camp', 'https://howstuffworks.com/tincidunt/eget/tempus.png', 2, '2020-01-06T14:49:33Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Alexander the Great', 'http://altervista.org/blandit/mi/in/porttitor.json', 2, '2020-09-26T15:22:11Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('My Bodyguard', 'http://senate.gov/amet/diam/in.html', 2, '2020-06-22T21:38:29Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Home Movie', 'https://shareasale.com/semper/porta/volutpat/quam/pede.js', 2, '2020-01-22T14:39:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Home Alone: The Holiday Heist', 'https://parallels.com/libero.xml', 2, '2020-07-21T06:58:52Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Sky West and Crooked (Gypsy Girl)', 'https://google.ru/tempus.js', 2, '2020-02-13T07:44:39Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Our Town', 'https://naver.com/quisque/id/justo/sit.png', 2, '2020-04-26T20:12:23Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Human Nature', 'http://nasa.gov/vel/sem/sed/sagittis.jpg', 2, '2020-06-02T08:14:44Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Grandfather, The (Abuelo, El)', 'https://cdbaby.com/rutrum/rutrum/neque/aenean/auctor.json', 2, '2020-12-26T00:15:25Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Saturday Night', 'http://examiner.com/ut/rhoncus/aliquet/pulvinar.json', 2, '2020-01-11T03:12:06Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Wisdom of Crocodiles, The (a.k.a. Immortality)', 'https://washingtonpost.com/congue/vivamus/metus/arcu.png', 2, '2020-09-06T16:13:08Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Shades of Fern (Stín kapradiny)', 'http://google.com.au/pellentesque.jsp', 2, '2020-08-25T14:18:28Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('That Certain Woman', 'https://symantec.com/sapien/cursus/vestibulum/proin.js', 2, '2020-04-20T06:17:50Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('They Call Me Trinity', 'https://zimbio.com/feugiat.aspx', 2, '2020-09-16T06:33:18Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Presto', 'http://walmart.com/sociis/natoque.html', 2, '2020-01-12T23:15:09Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Strange Love of Martha Ivers, The', 'http://merriam-webster.com/primis.aspx', 2, '2020-02-25T23:40:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('The Concert for Bangladesh', 'http://dyndns.org/tortor/sollicitudin/mi/sit.xml', 2, '2020-12-04T10:42:24Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Visitor, The', 'http://indiatimes.com/id/lobortis/convallis/tortor.jpg', 2, '2020-10-30T16:00:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Last Hurrah, The', 'https://exblog.jp/viverra.aspx', 2, '2020-10-18T10:05:58Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Murder by Decree', 'https://clickbank.net/pellentesque.xml', 2, '2020-03-14T09:24:07Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Just Between Friends', 'http://wiley.com/enim/leo.jsp', 2, '2020-08-04T03:45:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Message, The (a.k.a. Mohammad: Messenger of God)', 'https://wisc.edu/habitasse/platea/dictumst/morbi/vestibulum/velit/id.aspx', 2, '2020-06-21T23:11:21Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Man in the Glass Booth, The', 'http://nymag.com/magnis/dis/parturient/montes/nascetur.jpg', 2, '2020-06-28T19:45:40Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Day of the Dead 2: Contagium', 'https://zimbio.com/semper/est/quam/pharetra/magna.xml', 2, '2020-02-08T20:09:22Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Surfwise', 'https://sciencedaily.com/pede/libero/quis/orci.html', 2, '2020-10-27T22:27:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('The Valley of Gwangi', 'http://go.com/mus/etiam.aspx', 2, '2020-08-02T03:37:14Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Woman Always Pays, The (Afgrunden) (Abyss, The)', 'https://hexun.com/pellentesque/at.html', 2, '2020-03-30T23:03:55Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Cobra', 'https://ning.com/justo.aspx', 2, '2020-08-10T09:59:35Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Die Is Cast, The (La suerte está echada)', 'http://pagesperso-orange.fr/lacus/morbi.js', 2, '2020-06-25T04:19:44Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Kurt Cobain: Montage of Heck', 'http://tripod.com/volutpat/in/congue.aspx', 2, '2021-01-01T17:01:40Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('X2: X-Men United', 'https://indiatimes.com/imperdiet/et/commodo/vulputate/justo/in/blandit.png', 2, '2020-07-04T07:32:55Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Modulations', 'http://dailymail.co.uk/sapien/arcu/sed.js', 2, '2020-04-21T01:39:09Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Half a Loaf of Kung Fu (Dian zhi gong fu gan chian chan)', 'http://ihg.com/potenti/nullam/porttitor.html', 2, '2020-05-09T12:52:49Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Cartoonist: Jeff Smith, BONE and the Changing Face of Comics, The', 'http://nyu.edu/quisque/id.aspx', 2, '2020-03-11T20:39:40Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Ego', 'http://stanford.edu/non/ligula/pellentesque/ultrices/phasellus/id.png', 2, '2020-08-01T04:15:14Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Die Bademeister – Weiber, saufen, Leben retten', 'http://wiley.com/dictumst/maecenas/ut/massa/quis/augue/luctus.png', 2, '2020-09-09T10:30:46Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Lost Missile, The', 'https://ted.com/mauris/enim.js', 2, '2020-01-05T19:37:10Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Marathon Family, The (Maratonci Trce Pocasni Krug)', 'http://biblegateway.com/id/luctus.png', 2, '2020-01-26T21:38:30Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Viper in the Fist', 'https://berkeley.edu/adipiscing/elit/proin/risus/praesent/lectus/vestibulum.xml', 2, '2020-10-20T09:15:43Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Slaughter', 'https://amazon.co.jp/egestas/metus/aenean/fermentum.html', 2, '2020-08-02T22:34:57Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Hitch Hike (Autostop rosso sangue) (Naked Prey, The)', 'https://wordpress.com/sagittis/nam/congue/risus/semper/porta.xml', 2, '2020-10-20T23:26:08Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('The Face Behind the Mask', 'https://google.com/magna/ac/consequat/metus/sapien.js', 2, '2020-09-02T05:24:28Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Belle Starr', 'http://cocolog-nifty.com/consequat/metus/sapien/ut/nunc/vestibulum.js', 2, '2020-01-26T03:25:57Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Stuart Little 3: Call of the Wild', 'http://goo.ne.jp/augue/aliquam/erat/volutpat/in/congue.png', 2, '2020-08-20T17:27:28Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Sentimental Swordsman, The (To ching chien ko wu ching chien)', 'https://blogs.com/pulvinar.js', 2, '2020-01-23T13:41:12Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('We Need to Talk About Kevin', 'http://wunderground.com/mi/sit/amet/lobortis/sapien.js', 2, '2020-06-17T10:53:43Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Paris Belongs to Us (Paris nous appartient)', 'https://typepad.com/fusce/consequat/nulla.jpg', 2, '2020-04-20T06:54:32Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Swimming Pool, The (La piscine)', 'https://privacy.gov.au/amet/consectetuer.xml', 2, '2020-12-31T00:58:37Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Iceman Cometh, The', 'https://istockphoto.com/est.json', 2, '2020-11-16T22:36:54Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Crazy Love (a.k.a. Love Is a Dog from Hell)', 'http://acquirethisname.com/nec/sem/duis/aliquam/convallis/nunc/proin.jsp', 2, '2020-05-19T07:50:06Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Serving Sara', 'http://telegraph.co.uk/tempor/convallis/nulla.jsp', 2, '2020-05-01T19:48:45Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Yours, Mine and Ours', 'https://java.com/in.aspx', 2, '2020-03-05T06:26:11Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Rebel, The', 'http://cbslocal.com/erat/id/mauris.js', 2, '2020-05-03T15:05:51Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Lord of the Flies', 'http://globo.com/mauris/enim/leo/rhoncus/sed.jpg', 2, '2020-01-10T16:49:34Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Antz', 'https://addthis.com/accumsan/felis/ut/at/dolor/quis.jsp', 2, '2020-09-13T17:35:14Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Mummy''s Tomb, The', 'http://friendfeed.com/cras/in/purus/eu.json', 2, '2020-12-16T19:29:15Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Exploding Girl, The', 'https://marriott.com/diam/in.jpg', 2, '2020-11-16T02:03:58Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Talented Mr. Ripley, The', 'https://reuters.com/pede/libero.aspx', 2, '2020-12-08T07:45:29Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('HazMat', 'http://discuz.net/mauris/vulputate.json', 2, '2020-03-22T22:11:59Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Great Silence, The (Grande silenzio, Il)', 'http://sohu.com/dolor/quis.aspx', 2, '2020-02-14T13:24:39Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Something to Talk About', 'http://networksolutions.com/maecenas/rhoncus/aliquam/lacus.xml', 2, '2020-03-13T08:35:32Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('47  Ronin (Shijûshichinin no shikaku)', 'http://pcworld.com/sollicitudin/ut/suscipit.html', 2, '2020-12-16T18:34:45Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Little Big League', 'http://redcross.org/praesent/blandit/nam/nulla/integer.json', 2, '2020-05-13T01:56:19Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Evan Almighty', 'http://edublogs.org/pretium/nisl/ut/volutpat/sapien/arcu/sed.html', 2, '2020-10-04T08:17:52Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Brass Target', 'https://wikispaces.com/vivamus/metus/arcu/adipiscing/molestie/hendrerit.json', 2, '2020-05-22T01:44:56Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Lost & Found', 'http://archive.org/cras/pellentesque/volutpat.json', 2, '2020-10-02T22:42:15Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Take Out', 'http://ox.ac.uk/vestibulum.aspx', 2, '2020-08-30T05:18:54Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Little Fish', 'https://google.ru/lacus/curabitur/at/ipsum/ac.html', 2, '2020-05-01T07:03:55Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Godspeed', 'https://ovh.net/morbi/non/lectus/aliquam/sit.jpg', 2, '2020-05-28T13:02:39Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Blonde Crazy', 'https://soundcloud.com/eget/tempus/vel/pede/morbi.js', 2, '2020-07-25T01:43:03Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Brimstone and Treacle', 'http://shinystat.com/quis/turpis/eget.html', 2, '2020-10-23T11:22:08Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('My Name Is Nobody (Il Mio nome è Nessuno)', 'https://home.pl/gravida/nisi/at/nibh/in/hac/habitasse.xml', 2, '2020-05-05T18:02:53Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Ernest Goes to Camp', 'http://youtu.be/ut/massa/quis/augue/luctus/tincidunt/nulla.jsp', 2, '2020-04-08T19:20:11Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Little Bit of Heaven, A', 'https://flickr.com/orci/luctus/et.jsp', 2, '2020-06-17T22:37:32Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Man on the Train (Homme du train, L'')', 'http://github.io/et/eros/vestibulum/ac/est.html', 2, '2020-08-15T03:35:39Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Murder of Fred Hampton, The', 'https://symantec.com/a/suscipit/nulla/elit/ac/nulla.js', 2, '2020-08-05T13:53:36Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Daniel', 'https://jugem.jp/felis.aspx', 2, '2020-06-14T17:25:32Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Deep End, The', 'http://virginia.edu/ipsum/primis/in/faucibus.jsp', 2, '2020-05-02T02:26:22Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Comic Book: The Movie', 'https://bluehost.com/cubilia/curae/donec/pharetra/magna.jsp', 2, '2021-01-01T13:08:16Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Hit Squad', 'http://youtube.com/rutrum/nulla/nunc/purus/phasellus/in/felis.html', 2, '2020-05-19T07:39:41Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Surprise', 'https://live.com/eleifend/donec/ut/dolor/morbi/vel.aspx', 2, '2020-04-14T15:56:10Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Jack-Jack Attack', 'http://illinois.edu/eget/massa/tempor.html', 2, '2020-07-10T21:24:37Z');
        insert into feed (title, "imageUrl", "creatorId", "createdAt") values ('Twin Sisters (De tweeling)', 'https://usgs.gov/nisl/duis/ac/nibh/fusce.jsp', 2, '2020-12-03T10:11:43Z');
        `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
