export const flairs = {
  angular: "angularjs.png",
  bash: "console--v2.png",
  c: "c-programming.png",
  cSharp: "c-sharp-logo.png",
  cpp: "c-plus-plus.png",
  css: "css3.png",
  dart: "dart.png",
  docker: "docker.png",
  elixir: "phoenix-framework.png",
  flutter: "flutter.png",
  go: "golang.png",
  graphql: "graphql.png",
  haskell: "haskell.png",
  html: "html-5.png",
  ionic: "ionic.png",
  java: "java-coffee-cup-logo.png",
  javascript: "javascript.png",
  kotlin: "kotlin.png",
  kubernetes: "kubernetes.png",
  php: "php-logo.png",
  python: "python.png",
  postgresql: "postgreesql.png",
  react: "react-native.png",
  "react-native": "react-native.png",
  ruby: "ruby-programming-language.png",
  // rust: "rust.png",
  svelte: "svelte.png",
  swift: "swift.png",
  typescript: "typescript.png",
  vue: "vue-js.png",
};
